# Generated by Django 5.0.2 on 2024-04-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='icon',
            field=models.CharField(blank=True, null=True),
        ),
    ]
